### PR TITLE
Implement optional interactive model search for downloader

### PR DESCRIPTION
**Pull request by paralin**
This commit adds a optional "search huggingface" feature to the downloader.

### CODE REVIEW

**Comment by matteo-grella** [comment]
Thanks @paralin , this is a cool improvement!

I noticed that in addition to the new functionality, you also changed the command-line arguments parser.

Do you have a strong option to use `cli` versus `docopt-go`? 

We should pick one and align the rest. I'm pretty new to Go, so I don't have a clear idea which is better yet. What do you think @evanmcclure ?

Additionally, I am not a big fan of public variables, but I am also not that against keeping as such the `repo`, `model` and `overwrite` as they live in the `main.go` only.

Before accepting the pool request, I would ask you a few changes. Hope you don't mind!

In particular, I'd propose the following:
 - Rename `Model` to `ModelCard`;
 - Move `ModelCard`, `LookupFromHuggingFace()`, `ParseSearchResults()` into the file `downloader.go` just below `DownloadHuggingFacePreTrained()`;
 - Set the url `https://huggingface.co/models` as a const to be used into `LookupFromHuggingFace()`.

Minors:

Following your direction  of displaying "suggested" models, enriching the list in this way makes a lot of sense:

```go
// Excellent models to start with.
var models = []string{
    // suggested models for question-answering
    "deepset/bert-base-cased-squad2",
    // suggested models for real/fake token discrimination
    "google/electra-base-discriminator",
    // suggested models for masked tokens prediction
    "bert-base-cased",
    "bert-base-multilingual-cased",
    "bert-base-german-cased",
}
```

Should you be too busy, I can perform a manual merge by myself. Let me know :)

Thanks,

Matteo

**Comment by paralin** [comment]
I would recommend 100% using urfave/cli, the structure you see here for flags + sub-commands is what I've used to build 5 production services and numerous other projects over the last few years.

**Comment by paralin** [comment]
I can add another patch in the future to split some of this code into sub-packages inside the spago library which would allow api consumers to access the models database, for example.

**Comment by paralin** [comment]
Standby I will get rid of the global vars

**Comment by paralin** [comment]
- [X] Rename Model to ModelCard;

> Move ModelCard, LookupFromHuggingFace(), ParseSearchResults() into the file downloader.go just below DownloadHuggingFacePreTrained();

It's best to have one top-level struct per file with attached funcs, rather than define a bunch of structs together in one file, whenever possible.

> Set the url https://huggingface.co/models as a const to be used into LookupFromHuggingFace().

Done, also it's a flag now as well.

**Comment by paralin** [comment]
Modularized the code so that it could be split into a "cli" package easily

**Comment by paralin** [comment]
```
NAME:
   huggingfaceimporter - import data to a target path

USAGE:
   huggingfaceimporter [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --repo DIR        Directory to download the model [default: DIR] (default: "~/.spago/") [$SPAGO_REPO]
   --model value     name of the model to load [$SPAGO_MODEL]
   --models-url URL  url to lookup models from: URL (default: "https://huggingface.co/models") [$SPAGO_MODELS_URL]
   --overwrite       overwrite files if they exist already [$SPAGO_OVERWRITE]
   --help, -h        show help

```

**Comment by evanmcclure** [comment]
Regarding command-line flags parsing, I usually use the builtin flag package
for simple programs. For large programs with multiple sub-commands, I use
spf13/pflag as part of Cobra Command. One annoyance with any of those
approaches is that the usage/help text must be perpetually synced with any
changes to actual flag definitions.

The package docopt-go is growing on me. The usage is the source of the flag
definitions. I'd prefer to keep using docopt-go unless there's a need to
change it in the future.

**Comment by paralin** [comment]
@evanmcclure Please check the diff on this patch set. Take a look at how this CLI package doesn't require you to write the help text manually. Cobra is extremely over-complicated and messy, IMO.

**Comment by matteo-grella** [comment]
Ok @paralin , let's go for it!

**Comment by evanmcclure** [comment]
It's "crispier" than the current implementation, and I like the explicit
environment variable bindings. You've changed my mind.

**Comment by paralin** [comment]
@evanmcclure Glad to hear it! Having tried both approaches, this has never failed me (yet)!

**Pull request merged**
